apiVersion: v1
kind: ConfigMap
metadata:
  name: mount-config
  namespace: rook-ceph
data:
  mount.sh: |
    #!/bin/bash
    mon_endpoints=$(grep mon_host /etc/ceph/ceph.conf | awk '{print $3}')
    my_secret=$(grep key /etc/ceph/keyring | awk '{print $3}')
    sudo mount -t ceph -o mds_namespace=myfs-ec,name=admin,secret=$my_secret $mon_endpoints:/ /mnt/cluster
---
apiVersion: apps/v1
kind: Deployment
# kind: DaemonSet
metadata:
  name: rook-direct-mount
  namespace: rook-ceph
  labels:
    app: rook-direct-mount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-direct-mount
  template:
    metadata:
      labels:
        app: rook-direct-mount
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: rook-direct-mount
        image: rook/ceph:master
        command: ["/tini"]
        args: ["-g", "--", "/usr/local/bin/toolbox.sh"]
        imagePullPolicy: IfNotPresent
        env:
          # https://github.com/rook/rook/blob/release-1.2/Documentation/ceph-advanced-configuration.md
          - name: ROOK_ADMIN_SECRET
            valueFrom:
              secretKeyRef:
                name: rook-ceph-mon
                key: admin-secret
        securityContext:
          privileged: true
        lifecycle:
          postStart:
            exec:
              command: ["bash /mount.sh"]
          preStop:
            exec:
              command: ["sudo umount /mnt/cluster"]
        volumeMounts:
          - mountPath: /dev
            name: dev
          - mountPath: /sys/bus
            name: sysbus
          - mountPath: /lib/modules
            name: libmodules
          - name: mon-endpoint-volume
            mountPath: /etc/rook
          - name: mount-path
            mountPath: /mnt/cluster
            mountPropagation: Bidirectional
          - name: mount-config
            mountPath: /mount.sh
            subPath: mount.sh
      # if hostNetwork: false, the "rbd map" command hangs, see https://github.com/rook/rook/issues/2021
      hostNetwork: true
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: sysbus
          hostPath:
            path: /sys/bus
        - name: libmodules
          hostPath:
            path: /lib/modules
        - name: mon-endpoint-volume
          configMap:
            name: rook-ceph-mon-endpoints
            items:
            - key: data
              path: mon-endpoints
        - name: mount-path
          # https://kubernetes.io/docs/concepts/storage/volumes/#hostpath
          hostPath:
            path: /mnt/cluster
            type: DirectoryOrCreate
        - name: mount-config
          configMap:
            name: mount-config