# https://github.com/rook/rook/blob/master/Documentation/ceph-filesystem-crd.md
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: myfs-ec
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: osd
    replicated:
      size: 2
    deviceClass: ssd
  dataPools:
    - failureDomain: osd
      erasureCoded:
        dataChunks: 2
        codingChunks: 1
      deviceClass: hdd
  preservePoolsOnDelete: false
  metadataServer:
    activeCount: 1
    activeStandby: true
    annotations:
    placement:
    resources: