# https://github.com/rook/rook/blob/master/Documentation/ceph-filesystem-crd.md
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: mediafs-ssd
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: osd
    replicated:
      size: 1
    deviceClass: ssd
  dataPools:
    - failureDomain: osd
      replicated:
        size: 1
      deviceClass: ssd
  preservePoolsOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true
    annotations:
    placement:
    resources:
---
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: mediafs-ec
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: osd
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
    deviceClass: hdd
  dataPools:
    - failureDomain: osd
      erasureCoded:
        dataChunks: 2
        codingChunks: 1
      deviceClass: hdd
  preservePoolsOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true
    annotations:
    placement:
    resources: