version: '3'

services:
  openldap:
    # image: osixia/openldap
    container_name: ldap
    build:
      context: ${ROOT_DIR}/services/openldap
      dockerfile: Dockerfile
    env_file: ${ROOT_DIR}/services/openldap/openldap.env
    environment:
      # /etc/localtime fails on MacOS due to known bugs
      # https://github.com/docker/for-mac/issues/2396#issuecomment-444903734
      # https://github.com/docker/for-mac/issues/2396#issuecomment-446515510
      # It's also missing from RancherOS https://github.com/rancher/os/issues/2218
      # so we'll create a local environment variable:
      #   export ETC_LOCALTIME=$(readlink /etc/localtime)
      #   export LOCALTZ=$(echo $(readlink /etc/localtime) | awk -F'\/' '{print $6"/"$7}')
      # This essentially becomes a string of type Europe/London (for example)
      - TZ=${LOCALTZ}
    networks:
      - traefik_public
      - auth_internal
    ports:
      - 389:389

  keycloak:
    container_name: keycloak
    build:
      context: ${ROOT_DIR}/services/keycloak
      dockerfile: Dockerfile
    env_file: ${ROOT_DIR}/services/keycloak/keycloak.env
    environment:
      - TZ=${LOCALTZ}
    networks:
      - traefik_public
    # Ports aren't required when we're using Traefik to reverse proxy
    # ports:
    #   - 9990:9990
    #   - 8080:8080
    labels:
      - "trafeik.enable=true"
      - "traefik.backend=keycloak"
      # Auth
      - "traefik.frontend.rule=Host:${ANONDNS}; PathPrefix: /auth"
      - "traefik.port=8080"
      - "trafeik.docker.network=traefik_public"
  keycloak-db:
    container_name: keycloak_db
    env_file: ${ROOT_DIR}/services/keycloak/keycloak.env
    environment:
      - TZ=${LOCALTZ}
    image: postgres:10.1
    networks:
      - traefik_public
  keycloak-db-backup:
    container_name: keycloak_backup
    env_file: ${ROOT_DIR}/services/keycloak/keycloak-backup.env
    environment:
      - TZ=${LOCALTZ}
    image: postgres:10.1
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        pg_dump -Fc > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.psql
        (ls -t /dump/dump*.psql|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.psql)|sort|uniq -u|xargs rm -- {}
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    networks:
      - traefik_public

  ipupdater:
    container_name: dyndns
    build:
      context: ${ROOT_DIR}/services/ipupdater
      dockerfile: Dockerfile
    environment:
      - ANONDNS=${ANONDNS}
      - TOKEN=${TOKEN}

networks:
  # Used to expose openldap to keycloak
  traefik_public:
    external: true

  # Used to expose openldap to other apps which want to talk to LDAP
  auth_internal:
    external: true