# file: ~/cert-manager/letsencrypt.yaml
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: kube-system
spec:
  acme:
    # The ACME server URL and email address for ACME registration
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: lol@cats.com
    # Name of the secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
    # Enable HTTP01 validations
    - http01:
        ingress:
          class: nginx
    # Enable DNS validations
    - dns01:
        cloudflare:
          email: lol@cats.com
          apiKeySecretRef:
            name: cloudflare-apikey-secret
            key: apikey
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: kube-system
spec:
  acme:
    # The ACME server URL and email address for ACME registration
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lol@cats.com
    # Name of the secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    # Enable HTTP01 validations
    - http01:
        ingress:
          class: nginx
    # Enable DNS validations
    - dns01:
        cloudflare:
          email: lol@cats.com
          apiKeySecretRef:
            name: cloudflare-apikey-secret
            key: apikey