# file: ~/cert-manager/whoami-ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: whoami-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # cert-manager.io/issuer: "letsencrypt-staging"
spec:
  #tls:
  #- secretName: whoami-jamesveitch-dev-tls-staging
  #  hosts:
  #  - whoami.jamesveitch.dev
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: whoami
          servicePort: 80
