version: '3'

services:
  traefik:
    env_file: ${ROOT_DIR}/.env
    container_name: traefik
    image: traefik
    command: --docker --docker.watch --docker.domain=${ANONDNS} --logLevel=DEBUG
    networks:
      - traefik_public
      - auth_internal
    ports:
        # [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # allow traefik to monitor container status
      - ${ROOT_DIR}/services/traefik:/etc/traefik  # mount configs
    labels:
      - "trafeik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:${ANONDNS}; PathPrefixStrip: /traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_public"

networks:
  # Used to expose openldap to keycloak
  traefik_public:
    external: true
  
  # Used to expose openldap to other apps which want to talk to LDAP
  auth_internal:
    external: true
