version: '3'

services:
  keycloak:
    env_file: ${ROOT_DIR}/.env
    container_name: keycloak
    build:
      context: ${ROOT_DIR}/services/keycloak
      dockerfile: Dockerfile
    env_file: ${ROOT_DIR}/services/keycloak/keycloak.env
    environment:
      - TZ=${LOCALTZ}
    networks:
      - traefik_public
    labels:
      - "trafeik.enable=true"
      - "traefik.backend=keycloak"
      # Auth
      - "traefik.frontend.rule=Host:${ANONDNS}; PathPrefix: /auth"
      - "traefik.port=8080"
      - "trafeik.docker.network=traefik_public"
  keycloak-db:
    container_name: keycloak_db
    env_file: ${ROOT_DIR}/services/keycloak/keycloak.env
    environment:
      - TZ=${LOCALTZ}
    image: postgres:10.1
    networks:
      - traefik_public
  keycloak-db-backup:
    container_name: keycloak_backup
    env_file: ${ROOT_DIR}/services/keycloak/keycloak-backup.env
    environment:
      - TZ=${LOCALTZ}
    image: postgres:10.1
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        pg_dump -Fc > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.psql
        (ls -t /dump/dump*.psql|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.psql)|sort|uniq -u|xargs rm -- {}
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    networks:
      - traefik_public

networks:
  # Used to expose openldap to keycloak
  traefik_public:
    external: true
  
  # Used to expose openldap to other apps which want to talk to LDAP
  auth_internal:
    external: true
