version: '3'

services:
  ipupdater:
    env_file: ${ROOT_DIR}/.env
    container_name: dyndns
    build:
      context: ${ROOT_DIR}/services/ipupdater
      dockerfile: Dockerfile
    environment:
      - ANONDNS=${ANONDNS}  # dynamic hostname per anondns.net
      - TOKEN=${TOKEN}  # access token from anondns.net to update

